Mobile finish portfolio project.
TumiRantsane/Portfolio- pull request #2
Opened 2022-11-04 11:28 UTC by TumiRantsane

Changes and advancement done to meet alignment issues for a mobile device.

2022-11-04 12:13 UTC, Lizdev-05 approved these changes
Hi @TumiRantsane, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![approved](https://user-images.githubusercontent.com/73854999/199970080-d3e96ff6-d610-42bd-a4a8-b0faba2a8766.gif)

## Highlights
- Descriptive commit messages
- No linters error
- Project requirements are met
## Optional suggestions
- Please, don't open a new pull request when you are requested to make changes to avoid confusion.
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-07 13:38 UTC, ha-manel requested changes
# STATUS: REQUIRED CHANGES ♻️

## Hi @TumiRantsane👋 
Great job so far, There are some changes that need to be implemented in order to proceed to the next project 👍  

<img src="https://media3.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

## Highlights:  
* All tests passed ✔️
* Meaningful commit messages ✔️ 
* Professional README file ✔️

## Required Changes:
_Kindly check the comments below_

------
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-07 13:38 UTC, ha-manel commented on index.html
> +        <form id="form" action="#" method="post">
- [ ] Kindly add the link to `formspree` in the `action` attribute. it should be similar to this `https://formspree.io/f/{form_id}`

2022-11-07 13:38 UTC, ha-manel commented on index.html
> +              <label for="fname" class="fw-500 fz-17 lh-20">Name:</label>
- [ ] The form is looking good, however we should follow the design in Figma as much as possible. Kindly remove the labels to match the design 👍 

## Your design:
![image](https://user-images.githubusercontent.com/50721479/200324292-2b27210d-c065-46ce-8b61-c79c02d0c991.png)

## Figma design:
![image](https://user-images.githubusercontent.com/50721479/200324318-55b830cd-4011-4c5c-b7a7-acd91d07cddf.png)

2022-11-08 12:23 UTC, anagudelogu requested changes
Hi @TumiRantsane, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which haven't been addressed yet.

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

 ## Highlights
✅ Descriptive commit messages. 👍🏼
✅ Great use of GitHub flow. 💯 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-08 12:23 UTC, anagudelogu commented on index.html
> +        <form id="form" action="#" method="post">
- [ ] As requested by the previous reviewer, please use the [Formspree](https://formspree.io/html/) service to handle your contact's form submissions. 📜 It is important to be able to collect data from people that are trying to connect with us! Please, implement this. 🤓 🛠️ 

Requirements:
![image](https://user-images.githubusercontent.com/77069011/200561992-bef3eaa1-fccf-4d52-9e95-c14dfed34db8.png)

2022-11-08 13:18 UTC, BregornOriginal approved these changes
# Hi @TumiRantsane 🟢 🟢 🟢

## In my opinion, your project is ready for presentation!  There is nothing else to say other than... it's time to merge it 🥳 🥳 🥳


## Good luck! 🎉 🎉



Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2022-11-12 18:20 UTC, merged